name: Build master frontend
on: workflow_dispatch

env:
  working-directory: ./front

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Remove last version
      run: rm -rf ${{env.working-directory}}/build
    - name: Install Packages
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Build React JS
      run: npm run build
      working-directory: ${{env.working-directory}}
    - name: Zip release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'build.zip'
        path: '../'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "build.zip"
          token: ${{ secrets.GITHUB_TOKEN }}