name: Build alpha frontend
on:
  workflow_dispatch:
  push:
    branches:
      - alpha
    paths:
      - "front/**"

env:
  working-directory: ./front

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Remove last version
      run: rm -rf build
      working-directory: ${{env.working-directory}}
    - name: Change color to alpha palette App.css
      run: sed -i -e 's/1c8adb/F03780/g' src/App.css
      working-directory: ${{env.working-directory}}
    - name: Change color to alpha palette index.css
      run: sed -i -e 's/1c8adb/F03780/g' src/index.css
      working-directory: ${{env.working-directory}}
    - name: Install Packages
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Build React JS
      run: npm run build
      working-directory: ${{env.working-directory}}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Build frontend" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: alpha
